version: '3.4'
services:
  mysql-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: forcast
      MYSQL_USER: forcastuser
      MYSQL_PASSWORD: forcastpassword
    volumes:
      - mysql-data:/var/lib/mysql
  forcastweb-api:
    depends_on:
    - mysql-db
    image: forcastwebapi:0.0.1
    build:
      context: .
      dockerfile: ForecastWebApi/Dockerfile
    ports:
    - 80:80
volumes:
    mysql-data:
      driver: local

